[package]
name = "advent_of_code_2017"
version = "0.1.0"
authors = ["William Woodhead <william.woodhead@lux01.co.uk>"]

[dependencies]
nom = "^3.2"
petgraph = "0.4.10"
clap = "2.29.0"


[lib]
name = "advent_of_code_2017"
path = "src/lib.rs"

[[bin]]
name = "aoc_2017"
path = "src/main.rs"